# Generated by Django 3.1.2 on 2020-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github_checker', '0007_auto_20201005_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='closed_at',
        ),
    ]
