# Generated by Django 3.1.2 on 2020-10-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_checker', '0008_remove_pullrequest_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='has_hacktoberfest_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repo_has_hacktoberfest_topic',
            field=models.BooleanField(default=False),
        ),
    ]
