# Generated by Django 3.1.2 on 2020-10-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_checker', '0009_auto_20201014_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='alerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconfig',
            name='client',
            field=models.CharField(default='hacktoberfestchecker', max_length=255),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='pull_id',
            field=models.IntegerField(),
        ),
    ]
